### ISSUE TITLE
Routing error

### ISSUE THREAD

**Issue by josh-m-sharpe** [neerajsingh0101/admin_data#80]
Just installed the gem.  Have you seen this before I dig?

Started GET "/admin_data" for 127.0.0.1 at 2011-07-24 09:34:43 -0400
  Processing by AdminData::MainController#all_models as HTML
Completed 404 Not Found in 3ms

ActionController::RoutingError (No route matches {:controller=>"admin_data/search", :action=>"quick_search", :klass=>"charge/product_fee"}):
  actionpack (3.0.9) lib/action_dispatch/routing/route_set.rb:425:in `raise_routing_error'
  actionpack (3.0.9) lib/action_dispatch/routing/route_set.rb:398:in`generate'
  actionpack (3.0.9) lib/action_dispatch/routing/route_set.rb:454:in `generate'
  actionpack (3.0.9) lib/action_dispatch/routing/route_set.rb:482:in`url_for'
  actionpack (3.0.9) lib/action_dispatch/routing/url_for.rb:131:in `url_for'
  actionpack (3.0.9) lib/action_dispatch/routing/route_set.rb:195:in`admin_data_search_url'
  admin_data (1.0.1) app/controllers/admin_data/base_controller.rb:95:in `block in build_drop_down_for_klasses'
  admin_data (1.0.1) app/controllers/admin_data/base_controller.rb:90:in`each'
  admin_data (1.0.1) app/controllers/admin_data/base_controller.rb:90:in `inject'
  admin_data (1.0.1) app/controllers/admin_data/base_controller.rb:90:in`build_drop_down_for_klasses'
  activesupport (3.0.9) lib/active_support/callbacks.rb:467:in `_run__3288119691473672545__process_action__858045303645857939__callbacks'
  activesupport (3.0.9) lib/active_support/callbacks.rb:410:in`_run_process_action_callbacks'
  activesupport (3.0.9) lib/active_support/callbacks.rb:94:in `run_callbacks'
  actionpack (3.0.9) lib/abstract_controller/callbacks.rb:17:in`process_action'
  actionpack (3.0.9) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.0.9) lib/active_support/notifications.rb:52:in`block in instrument'
  activesupport (3.0.9) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (3.0.9) lib/active_support/notifications.rb:52:in`instrument'
  actionpack (3.0.9) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.0.9) lib/action_controller/metal/rescue.rb:17:in`process_action'
  actionpack (3.0.9) lib/abstract_controller/base.rb:119:in `process'
  actionpack (3.0.9) lib/abstract_controller/rendering.rb:41:in`process'
  actionpack (3.0.9) lib/action_controller/metal.rb:138:in `dispatch'
  actionpack (3.0.9) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.0.9) lib/action_controller/metal.rb:178:in `block in action'
  actionpack (3.0.9) lib/action_dispatch/routing/route_set.rb:62:in`call'
  actionpack (3.0.9) lib/action_dispatch/routing/route_set.rb:62:in `dispatch'
  actionpack (3.0.9) lib/action_dispatch/routing/route_set.rb:27:in`call'
  rack-mount (0.6.14) lib/rack/mount/route_set.rb:148:in `block in call'
  rack-mount (0.6.14) lib/rack/mount/code_generation.rb:93:in`block in recognize'
  rack-mount (0.6.14) lib/rack/mount/code_generation.rb:82:in `optimized_each'
  rack-mount (0.6.14) lib/rack/mount/code_generation.rb:92:in`recognize'
  rack-mount (0.6.14) lib/rack/mount/route_set.rb:139:in `call'
  actionpack (3.0.9) lib/action_dispatch/routing/route_set.rb:493:in`call'
  oa-core (0.2.6) lib/omniauth/strategy.rb:44:in `call!'
  oa-core (0.2.6) lib/omniauth/strategy.rb:30:in`call'
  oa-core (0.2.6) lib/omniauth/builder.rb:30:in `call'
  hoptoad_notifier (2.4.11) lib/hoptoad_notifier/rack.rb:27:in`call'
  sass (3.1.4) lib/sass/plugin/rack.rb:54:in `call'
  actionpack (3.0.9) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  actionpack (3.0.9) lib/action_dispatch/middleware/head.rb:14:in `call'
  rack (1.2.3) lib/rack/methodoverride.rb:24:in`call'
  actionpack (3.0.9) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.0.9) lib/action_dispatch/middleware/flash.rb:182:in`call'
  actionpack (3.0.9) lib/action_dispatch/middleware/session/abstract_store.rb:149:in `call'
  actionpack (3.0.9) lib/action_dispatch/middleware/cookies.rb:302:in`call'
  activerecord (3.0.9) lib/active_record/query_cache.rb:32:in `block in call'
  activerecord (3.0.9) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in`cache'
  activerecord (3.0.9) lib/active_record/query_cache.rb:12:in `cache'
  activerecord (3.0.9) lib/active_record/query_cache.rb:31:in`call'
  activerecord (3.0.9) lib/active_record/connection_adapters/abstract/connection_pool.rb:354:in `call'
  actionpack (3.0.9) lib/action_dispatch/middleware/callbacks.rb:46:in`block in call'
  activesupport (3.0.9) lib/active_support/callbacks.rb:421:in `_run_call_callbacks'
  actionpack (3.0.9) lib/action_dispatch/middleware/callbacks.rb:44:in`call'
  rack (1.2.3) lib/rack/sendfile.rb:107:in `call'
  actionpack (3.0.9) lib/action_dispatch/middleware/remote_ip.rb:48:in`call'
  actionpack (3.0.9) lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
  railties (3.0.9) lib/rails/rack/logger.rb:13:in`call'
  rack (1.2.3) lib/rack/runtime.rb:17:in `call'
  activesupport (3.0.9) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.2.3) lib/rack/lock.rb:11:in `block in call'
  <internal:prelude>:10:in`synchronize'
  rack (1.2.3) lib/rack/lock.rb:11:in `call'
  actionpack (3.0.9) lib/action_dispatch/middleware/static.rb:30:in`call'
  hoptoad_notifier (2.4.11) lib/hoptoad_notifier/user_informer.rb:12:in `call'
  railties (3.0.9) lib/rails/application.rb:168:in`call'
  railties (3.0.9) lib/rails/application.rb:77:in `method_missing'
  railties (3.0.9) lib/rails/rack/debugger.rb:21:in`call'
  railties (3.0.9) lib/rails/rack/log_tailer.rb:14:in `call'
  rack (1.2.3) lib/rack/content_length.rb:13:in`call'
  rack (1.2.3) lib/rack/handler/webrick.rb:52:in `service'
  /Users/jsharpe/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/httpserver.rb:111:in`service'
  /Users/jsharpe/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
  /Users/jsharpe/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/server.rb:183:in`block in start_thread'

Rendered /Users/jsharpe/.rvm/gems/ruby-1.9.2-p290@my_app/gems/actionpack-3.0.9/lib/action_dispatch/middleware/templates/rescues/routing_error.erb within rescues/layout (1.2ms)

**Comment by josh-m-sharpe** [comment]
$ rake routes | grep quick_search

admin_data_search /admin_data/quick_search/:klass  {:controller=>"admin_data/search", :action=>"quick_search"}

...server has been restarted.

**Comment by neerajsingh0101** [comment]
I have seen a few people complain when in their routes they have something similar to catch all routes. If you have any catch-all routes the try removing that temporarily and then give it a try.

And if you are able to find the culprit route the update me so that I can fix admin_data.
